In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
dog_data = pd.read_table(r'C:\Akshaya\dog_data.txt')
dog_data.head()

                                            sequence  class
0  ATGCCACAGCTAGATACATCCACCTGATTTATTATAATCTTTTCAA...      4
1  ATGAACGAAAATCTATTCGCTTCTTTCGCTGCCCCCTCAATAATAG...      4
2  ATGGAAACACCCTTCTACGGCGATGAGGCGCTGAGCGGCCTGGGCG...      6
3  ATGTGCACTAAAATGGAACAGCCCTTCTACCACGACGACTCATACG...      6
4  ATGAGCCGGCAGCTAAACAGAAGCCAGAACTGCTCCTTCAGTGACG...      0

In [4]:
def getkmers(sequence, size = 6 ):
    return[sequence[x:x+size].lower() for x in range(len(sequence) - size + 1)]

In [5]:
dog_data['words'] = dog_data.apply(lambda x: getkmers(x['sequence']),axis = 1)
dog_data = dog_data.drop('sequence', axis = 1)

In [6]:
dog_data.head()

   class                                              words
0      4  [atgcca, tgccac, gccaca, ccacag, cacagc, acagc...
1      4  [atgaac, tgaacg, gaacga, aacgaa, acgaaa, cgaaa...
2      6  [atggaa, tggaaa, ggaaac, gaaaca, aaacac, aacac...
3      6  [atgtgc, tgtgca, gtgcac, tgcact, gcacta, cacta...
4      0  [atgagc, tgagcc, gagccg, agccgg, gccggc, ccggc...

In [7]:
dog_texts= list(dog_data['words'])
for item in range (len(dog_texts)):
    dog_texts[item] = ' '.join(dog_texts[item])
y_data = dog_data.iloc[:, 0].values

In [8]:
print(dog_texts[2])

atggaa tggaaa ggaaac gaaaca aaacac aacacc acaccc caccct accctt cccttc ccttct cttcta ttctac tctacg ctacgg tacggc acggcg cggcga ggcgat gcgatg cgatga gatgag atgagg tgaggc gaggcg aggcgc ggcgct gcgctg cgctga gctgag ctgagc tgagcg gagcgg agcggc gcggcc cggcct ggcctg gcctgg cctggg ctgggc tgggcg gggcgg ggcggc gcggcg cggcgg ggcggc gcggcg cggcgt ggcgtc gcgtca cgtcag gtcagt tcagta cagtag agtagc gtagca tagcag agcagt gcagtg cagtgg agtggc gtggcg tggcgg ggcggc gcggcg cggcgg ggcggt gcggtg cggtgg ggtggt gtggta tggtag ggtagc gtagct tagctt agcttc gcttcg cttcgc ttcgcg tcgcgt cgcgtc gcgtcc cgtccc gtcccc tccccg ccccgg cccggg ccgggt cgggtc gggtcg ggtcgc gtcgcc tcgcct cgcctg gcctgt cctgtt ctgttt tgtttc gtttcc tttccc ttcccg tcccgg cccggg ccgggg cggggc ggggcg gggcgc ggcgcc gcgccc cgcccc gccccc cccccg ccccga cccgac ccgacg cgacgg gacggc acggcg cggcgg ggcggc gcggcg cggcga ggcgac gcgact cgactg gactgg actggc ctggca tggcag ggcagc gcagca cagcat agcatg gcatga catgat atgatg tgatga gatgaa atgaag tgaaga gaagaa aagaaa agaaag gaaaga aaagac aagacg agacgc gacgcg acgcgc cgcgct gcgctg cgctga gctgac ctgacg tgacgc gacgct acgctg cgctga gctgag ctgagc tgagcc gagcct agcctg gcctga cctgag ctgagc tgagcg gagcga agcgag gcgagc cgagca gagcag agcagg gcaggt caggtg aggtgg ggtggc gtggcg tggcgg ggcggc gcggcg cggcgg ggcggc gcggcg cggcgc ggcgct gcgctc cgctca gctcaa ctcaag tcaagc caagcc aagccc agcccg gcccgc cccgcg ccgcgg cgcggc gcggcc cggccg ggccgc gccgcg ccgcgc cgcgcc gcgccg cgccgc gccgcc ccgccc cgcccc gccccc cccccg ccccgg cccggc ccggcc cggccc ggcccc gccccc cccccc ccccct cccctg ccctgc cctgcg ctgcgc tgcgca gcgcac cgcacc gcaccg caccga accgac ccgacg cgacgg gacggc acggcg cggcgc ggcgcc gcgccc cgcccc gcccca ccccag cccagg ccaggc caggca aggcac ggcacg gcacgg cacggc acggcg cggcgc ggcgcc gcgccc cgcccc gccccc cccccc cccccg ccccga cccgac ccgacg cgacgg gacggc acggcc cggcct ggccta gcctac cctact ctactc tactct actctc ctctcc tctcct ctcctc tcctcg cctcgc ctcgcc tcgccc cgcccg gcccga cccgac ccgacc cgacct gacctg acctgg cctggg ctgggg tggggc ggggct gggctg ggctgc gctgct ctgctc tgctca gctcaa ctcaag tcaagc caagct aagctc agctcg gctcgc ctcgcc tcgcct cgcctc gcctcg cctcgc ctcgcc tcgccc cgcccg gcccga cccgag ccgagc cgagct gagctc agctcg gctcga ctcgag tcgagc cgagcg gagcgc agcgcc gcgcct cgccta gcctaa cctaat ctaatc taatca aatcat atcatc tcatcc catcca atccag tccagt ccagtc cagtcc agtcca gtccaa tccaac ccaacg caacgg aacggg acgggc cgggct gggctg ggctgg gctggt ctggtc tggtca ggtcac gtcacc tcacca caccac accacc ccacca caccac accacg ccacgc cacgcc acgccg cgccga gccgac ccgacg cgacga gacgag acgagc cgagca gagcac agcact gcactc cactca actcag ctcagt tcagtt cagttc agttcc gttcct ttcctc tcctct cctcta ctctac tctacc ctaccc tacccc acccca ccccaa cccaag ccaagg caaggt aaggtg aggtgg ggtggc gtggcg tggcgg ggcggc gcggcc cggcca ggccag gccagc ccagcg cagcga agcgag gcgagg cgagga gaggag aggagc ggagca gagcag agcagg gcagga caggag aggagt ggagtt gagttt agtttg gtttgc tttgcc ttgccg tgccga gccgag ccgagg cgaggg gagggc agggct gggctt ggcttc gcttcg cttcgt ttcgtc tcgtca cgtcaa gtcaag tcaagg caaggc aaggcc aggccc ggccct gccctg ccctgg cctgga ctggaa tggaag ggaaga gaagac aagact agactt gacttg acttgc cttgca ttgcac tgcaca gcacaa cacaag acaagc caagca aagcag agcaga gcagaa cagaac agaacc gaacca aaccag accagc ccagct cagctg agctgg gctggg ctgggc tgggca gggcac ggcacg gcacgg cacggg acgggc cgggcg gggcgc ggcgcg gcgcgg cgcggc gcggcc cggcct ggcctc gcctcg cctcgg ctcggc tcggca cggcag ggcagc gcagcc cagccg agccgc gccgcg ccgcgg cgcggc gcggcc cggccg ggccgc gccgcc ccgccg cgccgg gccgga ccggag cggagg ggagga gaggac aggacc ggaccc gaccct accctc ccctcg cctcgg ctcggg tcgggc cgggca gggcac ggcacg gcacgg cacggc acggct cggctg ggctgc gctgcg ctgcgg tgcggg gcgggc cgggcg gggcgc ggcgcc gcgccg cgccgc gccgcg ccgcgc cgcgcc gcgcct cgcctc gcctcc cctcct ctcctg tcctgg cctggc ctggcg tggcga ggcgaa gcgaac cgaact gaactg aactgg actggc ctggcc tggccc ggcccc gcccca ccccag cccagc ccagcg cagcgg agcggc gcggca cggcag ggcagc gcagcc cagcca agccac gccacg ccacgc cacgcc acgccc cgcccg gcccga cccgag ccgagg cgaggc gaggcg aggcgc ggcgcc gcgccc cgcccg gcccgt cccgtc ccgtct cgtcta gtctac tctacg ctacgc tacgcg acgcga cgcgaa gcgaac cgaacc gaacct aacctg acctga cctgag ctgagc tgagca gagcag agcagc gcagct cagcta agctac gctacg ctacgc tacgcg acgcgg cgcggg gcgggc cgggcg gggcgg ggcggc gcggca cggcac ggcacc gcaccg caccgg accggg ccgggg cggggg gggggt ggggtt gggttc ggttcg gttcgg ttcggg tcgggg cggggg gggggg gggggt ggggtg gggtgc ggtgct gtgctg tgctgc gctgcg ctgcga tgcgac gcgacg cgacgg gacggt acggtc cggtcg ggtcgc gtcgcc tcgcct cgcctt gccttc ccttcg cttcgc ttcgcc tcgccg cgccgc gccgcg ccgcgg cgcgga gcggag cggagc ggagcc gagcct agcctg gcctgt cctgtg ctgtgc tgtgcc gtgccc tgccct gccctt cccttc ccttcc cttccc ttccct tccctc ccctcc cctccg ctccgc tccgcc ccgcca cgccac gccacc ccaccg caccgc accgcc ccgccc cgcccc gccccc ccccca ccccag cccagg ccaggc caggcg aggcgc ggcgcg gcgcgc cgcgct gcgctg cgctgg gctggg ctgggg tggggc ggggcc gggccg ggccgc gccgcc ccgccc cgcccc gccccg ccccgc cccgcc ccgcct cgcctg gcctga cctgac ctgacc tgaccg gaccgc accgcg ccgcgc cgcgct gcgctc cgctca gctcaa ctcaag tcaagg caagga aaggat aggatg ggatga gatgag atgagc tgagcc gagccg agccgc gccgca ccgcag cgcaga gcagac cagacg agacgg gacggt acggtg cggtgc ggtgcc gtgccc tgcccg gcccga cccgac ccgacg cgacgt gacgtg acgtgc cgtgcc gtgcca tgccaa gccaag ccaagc caagct aagctt agcttc gcttcg cttcgg ttcggc tcggcg cggcga ggcgag gcgaga cgagag gagagc agagcc gagccc agcccg gcccgc cccgcc ccgccg cgccgt gccgtt ccgttg cgttgt gttgtc ttgtcg tgtcgc gtcgcc tcgccc cgccca gcccat cccatc ccatcg catcga atcgac tcgaca cgacat gacatg acatgg catgga atggac tggaca ggacac gacacg acacgc cacgca acgcag cgcagg gcagga caggag aggagc ggagcg gagcgc agcgca gcgcat cgcatt gcatta cattaa attaag ttaagg taaggc aaggcg aggcgg ggcgga gcggag cggagc ggagcg gagcgc agcgca gcgcaa cgcaag gcaagc caagcg aagcgg agcggc gcggct cggctg ggctgc gctgcg ctgcgc tgcgca gcgcaa cgcaac gcaacc caaccg aaccgc accgca ccgcat cgcatc gcatcg catcgc atcgct tcgctg cgctgc gctgcc ctgcct tgcctc gcctct cctcta ctctaa tctaag ctaagt taagtg aagtgc agtgcc gtgccg tgccgc gccgca ccgcaa cgcaag gcaagc caagcg aagcgc agcgca gcgcaa cgcaag gcaagc caagct aagctg agctgg gctgga ctggag tggagc ggagcg gagcgc agcgca gcgcat cgcatc gcatct catctc atctcg tctcgc ctcgcg tcgcgc cgcgcc gcgcct cgcctc gcctcg cctcga ctcgag tcgagg cgagga gaggag aggaga ggagaa gagaaa agaaag gaaagt aaagtg aagtga agtgaa gtgaag tgaaga gaagac aagacg agacgc gacgct acgctc cgctca gctcaa ctcaag tcaaga caagag aagagc agagcc gagcca agccag gccaga ccagaa cagaac agaaca gaacac aacacg acacgg cacgga acggag cggagc ggagct gagctg agctgg gctggc ctggcg tggcgt ggcgtc gcgtcc cgtcca gtccac tccaca ccacag cacagc acagcg cagcga agcgag gcgagc cgagcc gagcct agcctg gcctgc cctgct ctgctg tgctgc gctgcg ctgcgc tgcgcg gcgcga cgcgag gcgagc cgagca gagcag agcagg gcaggt caggtg aggtgg ggtggc gtggcg tggcgc ggcgca gcgcag cgcagc gcagct cagctc agctca gctcaa ctcaag tcaagc caagca aagcag agcaga gcagaa cagaag agaagg gaaggt aaggtc aggtcc ggtcct gtcctc tcctca cctcag ctcagc tcagcc cagcca agccac gccacg ccacgt cacgtc acgtca cgtcaa gtcaac tcaaca caacag aacagc acagcg cagcgg agcggc gcggct cggctg ggctgc gctgcc ctgcca tgccag gccagc ccagct cagctg agctgc gctgct ctgctg tgctgc gctgcc ctgccc tgcccc gcccca ccccag cccagc ccagca cagcac agcacc gcacca caccag accagg ccaggt caggtg aggtgt ggtgtc gtgtcc tgtccg gtccgc tccgcg ccgcgt cgcgta gcgtac cgtact gtactg tactga

In [9]:
y_data

array([4, 4, 6, 6, 0, 6, 0, 0, 0, 0, 0, 6, 6, 0, 0, 0, 6, 0, 0, 0, 0, 0,
       6, 0, 0, 0, 6, 0, 0, 6, 0, 0, 0, 0, 0, 0, 3, 0, 6, 0, 6, 0, 6, 0,
       6, 0, 0, 3, 3, 6, 6, 6, 6, 4, 0, 0, 4, 2, 0, 0, 0, 0, 6, 0, 6, 0,
       0, 5, 5, 6, 4, 6, 0, 0, 3, 6, 3, 6, 6, 6, 6, 6, 4, 6, 4, 1, 4, 0,
       0, 0, 6, 4, 4, 6, 6, 6, 6, 6, 4, 6, 6, 3, 3, 3, 3, 0, 6, 3, 3, 6,
       4, 4, 5, 6, 6, 1, 5, 2, 2, 1, 4, 2, 6, 3, 3, 6, 6, 6, 3, 3, 6, 6,
       6, 3, 6, 6, 2, 0, 0, 6, 6, 3, 3, 3, 0, 0, 4, 6, 6, 5, 1, 1, 0, 0,
       0, 4, 0, 4, 0, 0, 3, 4, 6, 0, 6, 6, 3, 4, 0, 6, 6, 1, 2, 2, 2, 3,
       6, 2, 2, 2, 6, 0, 0, 6, 6, 0, 0, 1, 6, 5, 5, 6, 0, 6, 0, 0, 4, 0,
       0, 3, 4, 0, 0, 6, 6, 5, 5, 3, 4, 1, 0, 6, 5, 6, 6, 4, 4, 2, 2, 2,
       4, 6, 4, 4, 2, 1, 3, 6, 0, 6, 2, 3, 0, 0, 6, 0, 6, 4, 3, 1, 1, 4,
       6, 4, 4, 6, 3, 3, 2, 2, 1, 1, 3, 3, 4, 3, 0, 3, 5, 5, 5, 5, 5, 5,
       5, 2, 2, 4, 4, 6, 4, 4, 6, 6, 6, 0, 3, 3, 4, 3, 0, 0, 6, 0, 0, 6,
       6, 1, 5, 5, 0, 0, 6, 6, 1, 1, 1, 4, 2, 2, 3, 4, 3, 4, 4, 1, 4, 4,
       3, 1, 6, 1, 2, 2, 2, 5, 0, 0, 6, 6, 6, 6, 4, 3, 3, 4, 5, 5, 6, 6,
       0, 4, 1, 2, 4, 4, 3, 4, 4, 0, 0, 6, 0, 5, 4, 4, 4, 4, 0, 5, 3, 3,
       6, 6, 6, 6, 6, 3, 4, 4, 2, 2, 3, 6, 0, 0, 2, 6, 4, 4, 6, 2, 4, 4,
       4, 0, 6, 6, 6, 0, 6, 3, 2, 2, 4, 0, 6, 4, 6, 4, 4, 4, 6, 6, 6, 4,
       6, 6, 6, 2, 6, 6, 6, 6, 6, 5, 6, 0, 0, 0, 5, 5, 5, 4, 6, 6, 6, 6,
       1, 1, 6, 6, 1, 4, 1, 1, 3, 6, 6, 1, 3, 2, 2, 0, 0, 4, 3, 0, 0, 5,
       0, 1, 1, 1, 3, 0, 2, 2, 2, 3, 1, 6, 3, 3, 6, 6, 6, 6, 5, 5, 4, 6,
       4, 6, 6, 6, 2, 5, 5, 0, 0, 3, 6, 5, 5, 1, 1, 1, 6, 6, 6, 6, 1, 1,
       2, 6, 6, 4, 6, 1, 3, 3, 6, 1, 2, 6, 4, 4, 0, 6, 6, 6, 4, 6, 6, 6,
       6, 6, 2, 2, 6, 6, 6, 4, 4, 1, 6, 6, 6, 2, 2, 1, 1, 3, 6, 6, 2, 2,
       2, 2, 0, 6, 4, 1, 1, 6, 1, 3, 3, 4, 4, 4, 4, 6, 6, 1, 1, 1, 5, 1,
       1, 2, 2, 6, 6, 4, 4, 0, 6, 3, 5, 4, 1, 1, 1, 3, 5, 6, 6, 6, 6, 5,
       5, 6, 3, 6, 6, 4, 6, 4, 0, 1, 0, 3, 4, 6, 4, 4, 4, 6, 1, 1, 5, 5,
       2, 6, 6, 6, 4, 0, 3, 6, 3, 6, 6, 3, 3, 6, 6, 6, 4, 6, 6, 6, 4, 4,
       4, 3, 3, 6, 3, 4, 6, 6, 4, 1, 5, 5, 6, 0, 0, 4, 6, 6, 0, 0, 0, 6,
       4, 4, 6, 6, 6, 3, 4, 4, 4, 6, 3, 2, 5, 6, 1, 3, 0, 2, 6, 4, 4, 5,
       0, 4, 4, 4, 4, 6, 5, 6, 6, 6, 6, 2, 2, 1, 1, 4, 4, 3, 5, 5, 1, 5,
       4, 0, 6, 0, 1, 1, 6, 6, 6, 6, 6, 1, 3, 4, 3, 5, 1, 0, 6, 6, 6, 4,
       1, 5, 5, 4, 0, 0, 6, 2, 6, 3, 6, 6, 0, 3, 3, 3, 3, 4, 6, 6, 0, 4,
       4, 4, 6, 1, 3, 0, 4, 4, 1, 1, 1, 6, 4, 2, 2, 3, 1, 4, 4, 1, 1, 6,
       6, 5, 5, 6, 3, 4, 6, 6, 6, 6, 3, 6, 6, 6, 2, 2, 6, 6, 3, 2, 4, 4,
       4, 6, 6, 4, 6, 6, 6, 6, 6, 3, 3, 5, 2, 2, 3, 0, 0, 0, 6, 6, 3, 3,
       3, 5, 6, 6, 1, 1, 0, 6, 6, 6, 4, 5, 6, 3, 0, 4, 6, 4, 4, 6, 6, 3,
       5, 5, 6, 6, 1, 6])

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(4,4))
X = cv.fit_transform(dog_texts)

In [11]:
print(X.shape)

(820, 227149)

In [ ]:
dog_data['class'].value_counts().sort_index().plot.bar()

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y_data, test_size=0.20, random_state=42)

In [18]:
print(X_train.shape)
print(X_test.shape)

(656, 227149)
(164, 227149)

In [19]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB(alpha=0.1)
classifier.fit(X_train, y_train)

MultinomialNB(alpha=0.1)

In [20]:
y_pred = classifier.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion Matrix\n")
print(pd.crosstab(pd.Series(y_test, name='Acutal'), pd.Series(y_pred, name='Predicted')))
def get_metrics(y_test, y_predicted):
    accuracy = accuracy_score(y_test, y_predicted)
    precision = precision_score(y_test, y_predicted, average='weighted')
    recall = recall_score(y_test, y_predicted, average='weighted')
    f1= f1_score(y_test, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy,precision, recall, f1 = get_metrics(y_test, y_pred)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 =%.3f" % (accuracy, precision, recall, f1))

Confusion Matrix

Predicted   0   1   2  3  4  5   6
Acutal
0          21   0   0  0  0  0   6
1           2  12   0  0  0  0   5
2           1   0  10  0  0  0   3
3           1   0   0  8  0  0   7
4           3   0   0  2  7  0  11
5           2   0   0  1  0  5   5
6           0   0   0  1  0  0  51
accuracy = 0.695
precision = 0.785
recall = 0.695
f1 =0.678